### ISSUE TITLE
The recv() implementation is not "cancel-safe"

### ISSUE THREAD

**Issue by ppershing** [AmitPr/async-oneshot-channel#1]
Just skimming through the code, I believe the implementation is wrong with respect of `recv()` future being dropped:
1) dropping the `recv()` future will not remove already registered waker. This is wrong semantics as it will then spuriously wake-up the task even if there is no interest in receiving data anymore
2) more importantly, caller is allowed to change waker if you call `recv()`, drop result and call `recv()` again. Current implementation will ignore this and thus use wrong waker.
  [Edit: you don't even need two futures, for a single future you are allowed to exchange waker in two successive `poll()`s and you can have spurious poll for whatever reason - the most trivial one being poll-only runtime which keeps polling future until it succeeds]

**Comment by AmitPr** [comment]
Thanks for the shout — was building around `tokio`-style runtimes and totally overlooked this. Thanks :)
